[package]
description = "Registar for Parity"
name = "registrar"
version = "0.0.1"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
ethabi = "6.0"
ethabi-derive = "6.0"
ethabi-contract = "6.0"
keccak-hash = "0.1"
