[package]
name = "std_test_override"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
name = "test"
path = "lib.rs"

[dependencies]
embedder_traits = { path = "../embedder_traits" }
