[package]
authors = ["The Rust Project Developers"]
name = "rustc_index"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_index"
path = "lib.rs"
doctest = false

[dependencies]
rustc_serialize = { path = "../libserialize", package = "serialize" }
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
