[llvm]
static-libstdcpp = true

[build]
host = ["x86_64-unknown-redox"]
target = ["x86_64-unknown-redox"]
docs = false
submodules = false
tools = ["src"]
verbose = 1

[rust]
backtrace = false
rpath = false
codegen-tests = false

[target.x86_64-unknown-redox]
cc = "x86_64-unknown-redox-gcc"
cxx = "x86_64-unknown-redox-g++"
ar = "x86_64-unknown-redox-ar"
linker = "x86_64-unknown-redox-gcc"
# Nasty path, please fix
llvm-config = "../../../bin/x86_64-unknown-redox-llvm-config"
crt-static = false
