[package]
authors = ["The Rust Project Developers"]
name = "syntax_expand"
version = "0.0.0"
edition = "2018"
build = false

[lib]
name = "syntax_expand"
path = "lib.rs"
doctest = false

[dependencies]
rustc_serialize = { path = "../libserialize", package = "serialize" }
log = "0.4"
syntax_pos = { path = "../libsyntax_pos" }
errors = { path = "../librustc_errors", package = "rustc_errors" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_lexer = { path = "../librustc_lexer" }
rustc_parse = { path = "../librustc_parse" }
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
syntax = { path = "../libsyntax" }
