# List of commit statuses that must pass on the merge commit before it is
# pushed to master.
status = [
  "continuous-integration/travis-ci/push",
]

# List of PR labels that may not be attached to a PR when it is r+-ed.
block_labels = [
  "blocked",
]

# Number of seconds from when a merge commit is created to when its statuses
# must pass. (Default = 3600).
#timeout_sec = 7200

# If set to true, and if the PR branch is on the same repository that bors-ng
# itself is on, the branch will be deleted.
delete_merged_branches = true
