[package]
name = "webvr"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "webvr"
path = "lib.rs"

[features]
googlevr = ['rust-webvr/googlevr']
oculusvr = ['rust-webvr/oculusvr']

[dependencies]
canvas_traits = {path = "../canvas_traits"}
compositing = {path = "../compositing"}
crossbeam-channel = "0.3"
euclid = "0.20"
ipc-channel = "0.12"
log = "0.4"
msg = {path = "../msg"}
rust-webvr = {version = "0.16", features = ["mock", "openvr", "vrexternal"]}
rust-webvr-api = "0.16"
servo_config = {path = "../config"}
sparkle = "0.1"
webvr_traits = {path = "../webvr_traits" }
