language: rust
dist: xenial
cache:
  cargo: false
rust:
  - nightly
install:
  # Use last well-known nightly for Rustfmt
  - rustup toolchain install nightly-2019-08-01
  - rustup component add rustfmt --toolchain nightly-2019-08-01
  # Required for Racer autoconfiguration
  - rustup component add rust-src
  - rustup component add rust-analysis
  - rustup component add rustc-dev
matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
    - os: windows
    - env: CLIPPY=true
      if: commit_message =~ /(?i:^update.*\b(clippy)\b)/
script:
  - |
    if [ "${CLIPPY}" = true ]; then
      cargo build -v --features "clippy"
      cargo test -v --features "clippy"
    else
      # Since the rls-* subcrates use crates.io-based dependencies of themselves it
      # makes sense to test them in isolation rather than just RLS itself
      (cd rls-analysis && cargo test -v && cargo +nightly-2019-08-01 fmt -- --check)
      (cd rls-data && cargo test -v && cargo +nightly-2019-08-01 fmt -- --check)
      (cd rls-rustc && cargo test -v && cargo +nightly-2019-08-01 fmt -- --check)
      (cd rls-span && cargo test -v && cargo +nightly-2019-08-01 fmt -- --check)
      (cd rls-vfs && cargo test -v && cargo +nightly-2019-08-01 fmt -- --check)
      cargo +nightly-2019-08-01 fmt -- --check
      cargo build -v
      cargo test -v
      cargo test test_tooltip_std -- --ignored
    fi

env:
  global:
    - RUST_BACKTRACE=1
    - RLS_TEST_WAIT_FOR_AGES=1
    - CARGO_INCREMENTAL=0
