# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
acid = {}
#audiod = {}
#autoconf = {}
#automake = {}
#bash = {}
#binutils = {}
#ca-certificates = {}
#cairo = {}
#cairodemo = {}
#cargo = {}
#cleye = {}
#cmatrix = {}
#contain = {}
coreutils = {}
#cpal = {}
#curl = {}
#dash = {}
#diffutils = {}
#dosbox = {}
#drivers = {}
#drivers-041 = {}
#duktape = {}
#eduke32 = {}
#exampled = {}
#expat = {}
#extrautils = {}
#fd = {}
#ffmpeg = {}
#findutils = {}
#freeciv = {}
#freedoom = {}
#freeglut = {}
#freetype = {}
#friar = {} # mio patch
#game-2048 = {}
#games = {}
#gawk = {}
#gcc = {}
#gears = {}
#generaluser-gs = {}
#gettext = {}
#gigalomania = {}
#git = {}
#glib = {}
#glium = {}
#glutin = {}
#gnu-binutils = {}
#gnu-grep = {}
#gnu-make = {}
#gstreamer = {}
#harfbuzz = {}
#hematite = {}
#init = {}
#installer = {}
#ion = {}
ipcd = {}
#jansson = {}
#keyboard-sfx = {}
#lci = {}
#libc-bench = {}
#libffi = {}
#libiconv = {}
#libjpeg = {}
#liborbital = {}
#libpng = {}
#libsodium = {}
#llvm = {}
logd = {}
#lua = {}
#mdp = {}
#mesa = {}
#mesa_glu = {}
#miniserve = {}
#nasm = {}
#ncdu = {}
#ncurses = {}
#ncursesw = {}
#netdb = {}
#netstack = {}
#netsurf = {}
#netutils = {}
#newlib = {}
#newlibtest = {}
nulld = {}
#openjazz = {}
#openssl = {}
#openttd = {}
#openttd-opengfx = {}
#openttd-openmsx = {}
#openttd-opensfx = {}
#orbdata = {}
#orbital = {}
#orbterm = {}
#orbutils = {}
#osdemo = {}
#pastel = {}
#patch = {}
#pcre = {}
#periodictable = {}
#perl = {}
#pixelcannon = {}
#pixman = {}
#pkgutils = {}
#powerline = {}
#prboom = {}
ptyd = {}
#python = {}
#qemu = {}
randd = {}
#readline = {} # ncurses
#redoxfs = {}
#redox-ssh = {}
#relibc = {}
#ripgrep = {}
#rodioplay = {}
#rs-nes = {}
#rust = {}
#rust64 = {}
#rust-cairo = {}
#rust-cairo-demo = {}
#rustual-boy = {}
#schismtracker = {}
#scummvm = {}
#sdl = {}
#sdl2 = {}
#sdl_gfx = {}
#sdl_image = {}
#sdl_mixer = {}
#sdl_ttf = {}
#sdl-player = {}
#sed = {}
#servo = {}
#shellstorm = {}
#smith = {}
#sodium = {}
#sopwith = {}
#ssh = {}
#syobonaction = {}
#terminfo = {}
#termplay = {}
#timidity = {}
#ttf-hack = {}
#userutils = {}
#uutils = {}
#vim = {}
#vttest = {}
#webrender = {}
#winit = {}
#xz = {}
zerod = {}
#zlib = {}

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

[[files]]
path = "/etc/init.d/00_base"
data = """
nulld
zerod
randd
ipcd
logd
ptyd
"""

[[files]]
path = "/etc/init.d/10_acid"
data = """
acid
acid create_test
acid switch
acid tls
shutdown
"""

[[files]]
path = "/usr/bin"
data = "/bin"
symlink = true

[[files]]
path = "/usr/games"
data = "/games"
symlink = true

[[files]]
path = "/usr/include"
data = "/include"
symlink = true

[[files]]
path = "/usr/lib"
data = "/lib"
symlink = true

[[files]]
path = "/usr/share"
data = "/share"
symlink = true

[[files]]
path = "/tmp"
data = ""
directory= true
# 0o1777
mode = 1023
