sys_includes = ["bits/sys/select.h", "sys/time.h"]
include_guard = "_SYS_SELECT_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export]
# fd_set is also defined in C because cbindgen is incompatible with mem::size_of booo
exclude = ["FD_SETSIZE", "fd_set"]

[export.rename]
"timeval" = "struct timeval"
