[package]
name = "rustdoc-tool"
version = "0.0.0"
authors = ["The Rust Project Developers"]
edition = "2018"

# Cargo adds a number of paths to the dylib search path on windows, which results in
# the wrong rustdoc being executed. To avoid the conflicting rustdocs, we name the "tool"
# rustdoc a different name.
[[bin]]
name = "rustdoc_tool_binary"
path = "main.rs"

[dependencies]
rustdoc = { path = "../../librustdoc" }
