sys_includes = ["stddef.h", "sys/socket.h", "netinet/in.h"]
include_guard = "_ARPA_INET_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"in_addr" = "struct in_addr"
