[package]
authors = ["The Rust Project Developers"]
name = "rustc_incremental"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_incremental"
path = "lib.rs"
doctest = false

[dependencies]
graphviz = { path = "../libgraphviz" }
log = "0.4"
rand = "0.7"
rustc = { path = "../librustc" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_serialize = { path = "../libserialize", package = "serialize" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_fs_util = { path = "../librustc_fs_util" }
