# This is the CI configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
acid = {}
audiod = {}
autoconf = {}
automake = {}
bash = {}
binutils = {}
ca-certificates = {}
cairo = {}
cairodemo = {}
cargo = {}
cleye = {}
cmatrix = {}
contain = {}
coreutils = {}
cpal = {}
curl = {}
dash = {}
diffutils = {}
dosbox = {}
drivers = {}
#drivers-041 = {}
#duktape = {} # strptime
eduke32 = {}
exampled = {}
expat = {}
extrautils = {}
#fd = {} #  ctrlc-3.1.1
ffmpeg = {}
findutils = {}
#freeciv = {}
freedoom = {}
#freeglut = {}
freetype = {}
#friar = {} # mio patch
game-2048 = {}
games = {}
#gawk = {} # langinfo.h
gcc = {}
gears = {}
generaluser-gs = {}
gettext = {}
gigalomania = {}
git = {}
glib = {}
glium = {}
glutin = {}
gnu-binutils = {}
gnu-grep = {}
gnu-make = {}
gstreamer = {}
harfbuzz = {}
hematite = {}
init = {}
installer = {}
ion = {}
ipcd = {}
jansson = {}
keyboard-sfx = {}
lci = {}
libc-bench = {}
libffi = {}
libiconv = {}
libjpeg = {}
liborbital = {}
libpng = {}
libsodium = {}
llvm = {}
logd = {}
#lua = {} # tmpnam
#mdp = {} # ncursesw
mesa = {}
mesa_glu = {}
#miniserve = {} # actix
nasm = {}
ncdu = {}
ncurses = {}
#ncursesw = {} # mkstemp configure hang
netdb = {}
netstack = {}
netsurf = {}
netutils = {}
#newlib = {} # obsolete
#newlibtest = {} # obsolete
nulld = {}
openjazz = {}
openssl = {}
openttd = {}
openttd-opengfx = {}
openttd-openmsx = {}
openttd-opensfx = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
osdemo = {}
pastel = {}
patch = {}
pcre = {}
periodictable = {}
#perl = {} # ctermid, tempnam, ttyname
pixelcannon = {}
pixman = {}
pkgutils = {}
powerline = {}
prboom = {}
ptyd = {}
#python = {} # getaddrinfo
#qemu = {}
randd = {}
readline = {}
redoxfs = {}
#redox-ssh = {}
relibc = {}
ripgrep = {}
rodioplay = {}
rs-nes = {}
#rust = {}
rust64 = {}
rust-cairo = {}
rust-cairo-demo = {}
rustual-boy = {}
schismtracker = {}
scummvm = {}
sdl = {}
#sdl2 = {}
sdl_gfx = {}
sdl_image = {}
sdl_mixer = {}
sdl-player = {}
sdl_ttf = {}
sed = {}
#servo = {} # some more crates to port
shellstorm = {}
smith = {}
sodium = {}
sopwith = {}
#ssh = {}
syobonaction = {}
terminfo = {}
termplay = {}
timidity = {}
ttf-hack = {}
userutils = {}
uutils = {}
vim = {}
vttest = {}
webrender = {}
winit = {}
xz = {}
zerod = {}
zlib = {}
