# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
drivers = {}
init = {}
redoxfs = {}

[[files]]
path="/etc/init.rc"
data="""
export PATH /bin
export TMPDIR /tmp
vesad T T G
stdio display:1
ps2d us
pcid /etc/pcid/initfs.toml
redoxfs --uuid $REDOXFS_UUID file
cd file:
export PATH file:/bin
run.d /etc/init.d
"""
