[package]
authors = ["The Rust Project Developers"]
name = "error_index_generator"
version = "0.0.0"
edition = "2018"
build = "build.rs"

[dependencies]
rustdoc = { path = "../../librustdoc" }

[build-dependencies]
walkdir = "2"

[[bin]]
name = "error_index_generator"
path = "main.rs"
