environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      MAKE: mingw32-make

install:
  # Install rust, x86_64-pc-windows-msvc host
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
