[package]
authors = ["The Rust Project Developers"]
name = "rustc_plugin_impl"
version = "0.0.0"
build = false
edition = "2018"

[lib]
name = "rustc_plugin_impl"
path = "lib.rs"
doctest = false

[dependencies]
rustc = { path = "../librustc" }
rustc_metadata = { path = "../librustc_metadata" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_error_codes = { path = "../librustc_error_codes" }
