[package]
name = "rayon-demo"
version = "0.0.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
publish = false

[dependencies]
rayon = { path = "../" }
cgmath = "0.14"
docopt = "0.7"
glium = "0.17"
rand = "0.3"
rustc-serialize = "0.3"
time = "0.1"
odds = "0.2"
lazy_static = "0.2.1"
fixedbitset = "0.1.5"
regex = "0.2"

[dev-dependencies]
num = "0.1.30"
