[package]
authors = ["The Rust Project Developers"]
name = "fmt_macros"
version = "0.0.0"
edition = "2018"

[lib]
name = "fmt_macros"
path = "lib.rs"

[dependencies]
syntax_pos = { path = "../libsyntax_pos" }
rustc_lexer = { path = "../librustc_lexer" }
