[package]

name = "time"
version = "0.1.42"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/time"
repository = "https://github.com/rust-lang/time"
documentation = "https://doc.rust-lang.org/time"
description = """
Utilities for working with time-related functions in Rust.
"""

[badges]
travis-ci = { repository = "rust-lang-deprecated/time" }
appveyor = { repository = "alexcrichton/time" }

[dependencies]
libc = "0.2.1"
rustc-serialize = { version = "0.3", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.0", features = ["std", "minwinbase", "minwindef", "ntdef", "profileapi", "sysinfoapi", "timezoneapi"] }

[dev-dependencies]
log = "0.4"
winapi = { version = "0.3.0", features = ["std", "processthreadsapi", "winbase"] }
