[target.aarch64-unknown-redox.dependencies.std]
features = ["panic_unwind"]

[target.x86_64-unknown-redox.dependencies.std]
features = ["panic_unwind"]
#features = ["panic_unwind", "backtrace"]

#[dependencies.test]
#stage = 1

