[package]
name = "rustc_macros"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
synstructure = "0.12.1"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"
quote = "1"
itertools = "0.8"
