[package]
name = "test_raftstore"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv = { path = "../../" }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
protobuf = "~2.0"
tempdir = "0.3"
raft = "0.4"
futures = "0.1"
tokio-timer = "0.2"
tokio-threadpool = "0.1"
grpcio = { version = "0.4", features = [ "secure" ] }
rand = "0.3"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
