[parity]
no_consensus = true
chain = "dev"

[mining]
reseal_min_period = 0
min_gas_price = 0

[rpc]
interface = "all"
apis = ["all"]
hosts = ["all"]

[ipfs]
enable = false # this is the default
hosts = ["all"]
