[package]
name = "bootloader-coreboot"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]

[lib]
name = "bootloader"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0.4"
coreboot-table = "0.1.4"
redox_syscall = "0.1.51"
spin = "0.5.0"
