[package]
authors = ["The Rust Project Developers"]
name = "rustc_errors"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_errors"
path = "lib.rs"
doctest = false

[dependencies]
log = "0.4"
rustc_serialize = { path = "../libserialize", package = "serialize" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_data_structures = { path = "../librustc_data_structures" }
unicode-width = "0.1.4"
atty = "0.2"
termcolor = "1.0"
annotate-snippets = "0.6.1"
term_size = "0.3.1"
