[package]
authors = ["The Rust Project Developers"]
name = "rustc_target"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_target"
path = "lib.rs"

[dependencies]
bitflags = "1.2.1"
log = "0.4"
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_macros = { path = "../librustc_macros" }
rustc_serialize = { path = "../libserialize", package = "serialize" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_index = { path = "../librustc_index" }
