[package]
authors = ["The Rust Project Developers"]
name = "rustc_apfloat"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_apfloat"
path = "lib.rs"

[dependencies]
bitflags = "1.2.1"
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
