[package]
name = "script_traits"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "script_traits"
path = "lib.rs"

[dependencies]
bluetooth_traits = {path = "../bluetooth_traits"}
canvas_traits = {path = "../canvas_traits"}
cookie = "0.11"
crossbeam-channel = "0.3"
devtools_traits = {path = "../devtools_traits"}
embedder_traits = {path = "../embedder_traits"}
euclid = "0.20"
gfx_traits = {path = "../gfx_traits"}
http = "0.1"
hyper = "0.12"
hyper_serde = "0.11"
ipc-channel = "0.12"
keyboard-types = "0.4.3"
libc = "0.2"
log = "0.4"
malloc_size_of = { path = "../malloc_size_of" }
malloc_size_of_derive = "0.1"
media = {path = "../media"}
msg = {path = "../msg"}
net_traits = {path = "../net_traits"}
pixels = {path = "../pixels"}
profile_traits = {path = "../profile_traits"}
serde = "1.0"
servo_atoms = {path = "../atoms"}
servo_url = {path = "../url"}
smallvec = "0.6"
style_traits = {path = "../style_traits", features = ["servo"]}
time = "0.1.12"
url = "2.0"
uuid = {version = "0.8", features = ["v4"]}
webdriver = "0.40"
webgpu = {path = "../webgpu"}
webrender_api = {git = "https://github.com/servo/webrender"}
webvr_traits = {path = "../webvr_traits"}
webxr-api = {git = "https://github.com/servo/webxr", features = ["ipc"]}
