[package]
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
name = "dom_struct"
publish = false
version = "0.0.1"

[dependencies]
quote = "1"
syn = { version = "1", default-features = false, features = ["clone-impls", "parsing"] }

[lib]
path = "lib.rs"
proc-macro = true
