language: rust

cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true
  include:

  # Test crates on their minimum Rust versions.
  - rust: 1.28.0
    name: "crossbeam on 1.28.0"
    script: ./ci/crossbeam.sh
  - rust: 1.26.0
    name: "crossbeam-channel on 1.26.0"
    script: ./ci/crossbeam-channel.sh
  - rust: 1.28.0
    name: "crossbeam-deque on 1.28.0"
    script: ./ci/crossbeam-deque.sh
  - rust: 1.26.0
    name: "crossbeam-epoch on 1.26.0"
    script: ./ci/crossbeam-epoch.sh
  - rust: 1.26.0
    name: "crossbeam-queue on 1.26.0"
    script: ./ci/crossbeam-queue.sh
  - rust: 1.28.0
    name: "crossbeam-skiplist on 1.28.0"
    script: ./ci/crossbeam-skiplist.sh
  - rust: 1.26.0
    name: "crossbeam-utils on 1.26.0"
    script: ./ci/crossbeam-utils.sh

  # Test crates on nightly Rust.
  - rust: nightly
    name: "crossbeam on nightly"
    script: ./ci/crossbeam.sh
  - rust: nightly
    name: "crossbeam-channel on nightly"
    script: ./ci/crossbeam-channel.sh
  - rust: nightly
    name: "crossbeam-deque on nightly"
    script: ./ci/crossbeam-deque.sh
  - rust: nightly
    name: "crossbeam-epoch on nightly"
    script: ./ci/crossbeam-epoch.sh
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise
          - llvm-toolchain-precise-3.8
        packages:
          - llvm-3.8
          - llvm-3.8-dev
          - clang-3.8
          - clang-3.8-dev
  - rust: nightly
    name: "crossbeam-queue on nightly"
    script: ./ci/crossbeam-queue.sh
  - rust: nightly
    name: "crossbeam-skiplist on nightly"
    script: ./ci/crossbeam-skiplist.sh
  - rust: nightly
    name: "crossbeam-utils on nightly"
    script: ./ci/crossbeam-utils.sh

  # Check for duplicate dependencies.
  - rust: nightly
    name: "dependency tree check"
    script: ./ci/dependencies.sh

  # Check formatting.
  - rust: stable
    name: "rustfmt"
    script: ./ci/rustfmt.sh
