[package]
name = "test_util"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv = { path = "../../" }
time = "0.1"
rand = "0.5"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
